### ISSUE TITLE
error: Bad owner/group

### ISSUE THREAD

**Issue by sdellenb** [jc21/docker-rpmbuild-centos7#1]
This is not an issue of the docker build, but it appears that the rpmbuild included with CentOS 7.5 (version 4.11.3) [has a bug](https://github.com/rpm-software-management/rpm/issues/2) that was [fixed in rpmbuild 4.14.2 3 years ago](https://github.com/rpm-software-management/rpm/commit/916d528b0bfcb33747e81a57021e01586aa82139).

> error: Bad owner/group: /home/rpmbuilder/rpmbuild/SOURCES/[SOURCE_ARCHIVE]

**Do you have a workaround for building?**

I tried renaming my user to "rpmbuilder" to match the one in the docker container, but I still get the same error.

Forgot to mention: I added the user to the docker user group instead of using `sudo`, but it doesn't work either way for me.
Full script output is like this:
```
[rpmbuilder@machine ~]$ ./bin/build.sh unbound-1.8.1.spec
Loaded plugins: fastestmirror, ovl
Cleaning repos: base centos-sclo-rh centos-sclo-sclo epel extras jc21 updates
Cleaning up everything
Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
BUILDING: /home/rpmbuilder/rpmbuild/SPECS/unbound-1.8.1.spec ...
Loaded plugins: fastestmirror, ovl
Enabling base-source repository
Enabling centos-sclo-rh-source repository
Enabling centos-sclo-sclo-source repository
Enabling epel-source repository
Enabling extras-source repository
Enabling updates-source repository
Determining fastest mirrors
 * epel: mirror.de.leaseweb.net
 * epel-source: mirror.de.leaseweb.net
Getting requirements for /home/rpmbuilder/rpmbuild/SPECS/unbound-1.8.1.spec
 --> flex-2.5.37-3.el7.x86_64
 --> Already installed : 1:openssl-devel-1.0.2k-12.el7.x86_64
 --> Already installed : libevent-devel-2.0.21-4.el7.x86_64
 --> Already installed : expat-devel-2.1.0-10.el7_3.x86_64
 --> Already installed : 1:pkgconfig-0.27.1-4.el7.x86_64
 --> python-devel-2.7.5-69.el7_5.x86_64
 --> swig-2.0.10-5.el7.x86_64
 --> Already installed : systemd-219-57.el7_5.1.x86_64
--> Running transaction check
---> Package flex.x86_64 0:2.5.37-3.el7 will be installed
---> Package python-devel.x86_64 0:2.7.5-69.el7_5 will be installed
---> Package swig.x86_64 0:2.0.10-5.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package             Arch          Version                 Repository      Size
================================================================================
Installing:
 flex                x86_64        2.5.37-3.el7            base           292 k
 python-devel        x86_64        2.7.5-69.el7_5          updates        397 k
 swig                x86_64        2.0.10-5.el7            base           1.3 M

Transaction Summary
================================================================================
Install  3 Packages

Total download size: 1.9 M
Installed size: 6.5 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                              6.2 MB/s | 1.9 MB  00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-devel-2.7.5-69.el7_5.x86_64                           1/3
  Installing : flex-2.5.37-3.el7.x86_64                                     2/3
  Installing : swig-2.0.10-5.el7.x86_64                                     3/3
  Verifying  : swig-2.0.10-5.el7.x86_64                                     1/3
  Verifying  : flex-2.5.37-3.el7.x86_64                                     2/3
  Verifying  : python-devel-2.7.5-69.el7_5.x86_64                           3/3

Installed:
  flex.x86_64 0:2.5.37-3.el7        python-devel.x86_64 0:2.7.5-69.el7_5
  swig.x86_64 0:2.0.10-5.el7

Complete!
error: Bad owner/group: /home/rpmbuilder/rpmbuild/SOURCES/unbound-1.8.1.tar.gz
```

**Update**: I found a workaround by matching the uid of the rpmbuilder user [in this line](https://github.com/jc21/docker-rpmbuild-centos7/blob/master/Dockerfile#L37):
```diff
 # Rpm User
-RUN adduser -G wheel rpmbuilder \
+RUN adduser -u 2020 -G wheel rpmbuilder \
```

**Comment by jc21** [comment]
Yeah I noticed this crap started happening in recent months for me and I didn't think too much of it. I was just wrapping my scripts in some chown calls:

```bash
# change ownership for build
sudo docker run --rm \
  -v $(pwd):/home/rpmbuilder/cwd \
  jc21/rpmbuild-centos7 sudo chown -R rpmbuilder:rpmbuilder /home/rpmbuilder/cwd

sudo docker run --rm \
  --name rpmbuild \
  -v $(pwd)/RPMS:/home/rpmbuilder/rpmbuild/RPMS \
  -v $(pwd)/SRPMS:/home/rpmbuilder/rpmbuild/SRPMS \
  -v $(pwd)/SPECS:/home/rpmbuilder/rpmbuild/SPECS \
  -v $(pwd)/SOURCES:/home/rpmbuilder/rpmbuild/SOURCES \
  jc21/rpmbuild-centos7 \
  /bin/build-spec /home/rpmbuilder/rpmbuild/SPECS/something.spec

# change ownership back
sudo docker run --rm \
  -v $(pwd):/home/rpmbuilder/cwd \
  jc21/rpmbuild-centos7 sudo chown -R `id -u`:`id -g` /home/rpmbuilder/cwd
```

I would definitely prefer to use the newer version of rpmbuild to avoid this, I'll research what the options are..

**Comment by jc21** [comment]
I've managed to build rpm-4.14.2 however it's just not going to install into Centos 7.5. It's previous libs are heavily used as dependencies in other packages. I think all we can do is to work around the problem.

From memory, I mostly encountered this error when the ID of the file's user/group did not exist in the Docker's `/etc/passwd` and `/etc/groups` files respectively. I don't encounter this problem in CI because the owner is always root which exists in the docker image too.

So from that, you could create your own docker image based on mine but just add users/groups with the id's you have on your docker host in the build.

**Comment by sdellenb** [comment]
> So from that, you could create your own docker image based on mine but just add users/groups with the id's you have on your docker host in the build.

That's exactly what I did.
I cloned the repo and added the uid for my rpmbuild user in the `adduser` statement of the Dockerfile.

Works like a charm! Thank's for providing this solution! 👍

**Comment by r2dedios** [comment]
And if you need to work with some users? (coworkers for example)

**Comment by jc21** [comment]
Take a look at [my build script here](https://github.com/jc21-rpm/terraform/blob/master/build). The main takeaways are that it will:
1. change ownership of the mounted folder inside the docker container you're using to build (line 51)
2. do the build (line 59)
3. revert ownership back to the uid/gid that is running the script, even on failure (line 75)
